# Generated by Django 4.2.9 on 2024-03-05 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='floor_plan',
            field=models.ImageField(blank=True, upload_to='floor_plans/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='listing',
            name='home_open',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='listing',
            name='video',
            field=models.URLField(blank=True),
        ),
    ]
