# Generated by Django 4.2.9 on 2024-03-06 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_floor_plan_listing_home_open_listing_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='garage',
            field=models.IntegerField(default=2),
        ),
    ]
