# Generated by Django 4.2.9 on 2024-03-07 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_listing_garage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='floor_plan',
            field=models.FileField(blank=True, null=True, upload_to='floor_plans/%Y/%m/%d'),
        ),
    ]
