# Generated by Django 4.2.9 on 2024-03-23 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_home_open_enquiries_alter_comingsoon_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
