# Generated by Django 4.2.9 on 2024-04-17 19:16

from django.db import migrations, models
import listings.models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_listing_photo_10_listing_photo_11_listing_photo_12_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='photo_1',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', validators=[listings.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_10',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', validators=[listings.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_11',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', validators=[listings.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_12',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', validators=[listings.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_2',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', validators=[listings.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_3',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', validators=[listings.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_4',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', validators=[listings.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_5',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', validators=[listings.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_6',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', validators=[listings.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_7',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', validators=[listings.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_8',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', validators=[listings.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_9',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', validators=[listings.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_main',
            field=models.ImageField(upload_to='photos/%Y/%m/%d', validators=[listings.models.validate_image_size]),
        ),
    ]
