# Generated by Django 4.2.9 on 2024-04-27 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_alter_listing_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='home_open_enquiries',
            options={'verbose_name_plural': 'Home_Open_Enquiries'},
        ),
        migrations.AlterModelOptions(
            name='listing',
            options={'verbose_name_plural': 'Listing'},
        ),
    ]
