# Generated by Django 4.2.9 on 2024-07-19 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_inspection_unsubscribedemail_listing_photo_13_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeOpen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='home_open_images/')),
                ('title', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
    ]
