# Generated by Django 4.2.9 on 2024-08-18 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0016_listing_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'verbose_name_plural': 'Listings'},
        ),
    ]
