# Generated by Django 4.2.9 on 2024-08-18 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0017_alter_listing_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'verbose_name_plural': 'Listing'},
        ),
    ]
