# Generated by Django 4.2.9 on 2024-08-18 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0018_alter_listing_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home_open_enquiries',
            name='Property',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
