# Generated by Django 4.2.9 on 2024-08-23 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0017_alter_listing_options_remove_listing_photo_1_and_more'),
        ('listings', '0019_alter_home_open_enquiries_property'),
    ]

    operations = [
    ]
