# Generated by Django 4.2.9 on 2024-08-23 10:56

from django.db import migrations, models
import listings.models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0020_merge_20240823_1846'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'verbose_name_plural': 'Listing'},
        ),
        migrations.AddField(
            model_name='listing',
            name='photo_1',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', validators=[listings.models.validate_image_size]),
        ),
        migrations.AddField(
            model_name='listing',
            name='photo_10',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', validators=[listings.models.validate_image_size]),
        ),
        migrations.AddField(
            model_name='listing',
            name='photo_11',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', validators=[listings.models.validate_image_size]),
        ),
        migrations.AddField(
            model_name='listing',
            name='photo_12',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', validators=[listings.models.validate_image_size]),
        ),
        migrations.AddField(
            model_name='listing',
            name='photo_13',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', validators=[listings.models.validate_image_size]),
        ),
        migrations.AddField(
            model_name='listing',
            name='photo_14',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', validators=[listings.models.validate_image_size]),
        ),
        migrations.AddField(
            model_name='listing',
            name='photo_15',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', validators=[listings.models.validate_image_size]),
        ),
        migrations.AddField(
            model_name='listing',
            name='photo_16',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', validators=[listings.models.validate_image_size]),
        ),
        migrations.AddField(
            model_name='listing',
            name='photo_17',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', validators=[listings.models.validate_image_size]),
        ),
        migrations.AddField(
            model_name='listing',
            name='photo_18',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', validators=[listings.models.validate_image_size]),
        ),
        migrations.AddField(
            model_name='listing',
            name='photo_2',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', validators=[listings.models.validate_image_size]),
        ),
        migrations.AddField(
            model_name='listing',
            name='photo_3',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', validators=[listings.models.validate_image_size]),
        ),
        migrations.AddField(
            model_name='listing',
            name='photo_4',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', validators=[listings.models.validate_image_size]),
        ),
        migrations.AddField(
            model_name='listing',
            name='photo_5',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', validators=[listings.models.validate_image_size]),
        ),
        migrations.AddField(
            model_name='listing',
            name='photo_6',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', validators=[listings.models.validate_image_size]),
        ),
        migrations.AddField(
            model_name='listing',
            name='photo_7',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', validators=[listings.models.validate_image_size]),
        ),
        migrations.AddField(
            model_name='listing',
            name='photo_8',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', validators=[listings.models.validate_image_size]),
        ),
        migrations.AddField(
            model_name='listing',
            name='photo_9',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', validators=[listings.models.validate_image_size]),
        ),
    ]
