# Generated by Django 4.2.9 on 2024-09-27 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0021_alter_listing_options_listing_photo_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeopen',
            name='day',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
