# Generated by Django 4.2.9 on 2024-10-24 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0022_homeopen_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeopen',
            name='listing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_opens', to='listings.listing'),
        ),
    ]
