# Generated by Django 4.2.9 on 2024-10-24 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0023_homeopen_listing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='lot_size',
        ),
    ]
