# Generated by Django 4.2.9 on 2024-10-24 23:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0024_remove_listing_lot_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='floor_plan',
            field=models.FileField(blank=True, default='floor_plans/default/default-floor-plan.pdf', upload_to='floor_plans/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
    ]
