# Generated by Django 4.2.7 on 2023-12-26 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SoldProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('sqft', models.IntegerField()),
                ('image1', models.ImageField(upload_to='sold_images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='sold_images/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='sold_images/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='sold_images/')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='sold_images/')),
                ('image6', models.ImageField(blank=True, null=True, upload_to='sold_images/')),
                ('image7', models.ImageField(blank=True, null=True, upload_to='sold_images/')),
                ('image8', models.ImageField(blank=True, null=True, upload_to='sold_images/')),
                ('image9', models.ImageField(blank=True, null=True, upload_to='sold_images/')),
                ('image10', models.ImageField(blank=True, null=True, upload_to='sold_images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='sold_videos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
