# Generated by Django 4.2.7 on 2023-12-28 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_award'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_image', models.ImageField(upload_to='about_images/')),
                ('background_image', models.ImageField(upload_to='about_images/')),
                ('logo_image', models.ImageField(upload_to='about_images/')),
                ('background_image2', models.ImageField(upload_to='about_images/')),
            ],
        ),
    ]
