# Generated by Django 4.2.7 on 2023-12-30 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='blog_images/')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('read_more_link', models.CharField(max_length=200)),
            ],
        ),
    ]
