# Generated by Django 4.2.7 on 2023-12-30 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='read_more_link',
        ),
        migrations.AddField(
            model_name='blog',
            name='full_content',
            field=models.TextField(default='full_content'),
        ),
    ]
