# Generated by Django 4.2.7 on 2024-01-24 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_textreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('bedrooms', models.PositiveIntegerField()),
                ('bathrooms', models.PositiveIntegerField()),
                ('garage', models.BooleanField(default=False)),
                ('photo', models.ImageField(upload_to='feedback_photos/')),
                ('star_ratings', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('empty_stars', models.PositiveIntegerField()),
                ('review_title', models.CharField(max_length=255)),
                ('review_detail', models.TextField()),
            ],
        ),
    ]
