# Generated by Django 4.2.7 on 2024-01-24 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_feedbackcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='textreview',
            name='name',
            field=models.TextField(default='Default Name'),
        ),
    ]
