# Generated by Django 4.2.7 on 2024-01-25 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_textreview_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='ppre_logo',
            field=models.ImageField(default='about_images/default_logo.jpg', upload_to='about_images/'),
        ),
    ]
