# Generated by Django 4.2.7 on 2024-01-25 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_about_ppre_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackcard',
            name='garage',
            field=models.PositiveIntegerField(default='0'),
        ),
    ]
