# Generated by Django 4.2.7 on 2024-02-02 18:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_alter_feedbackcard_star_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackcard',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
