# Generated by Django 4.2.9 on 2024-02-21 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_remove_certificate_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='description',
            field=models.TextField(default='Default Description'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='title',
            field=models.CharField(default='Default Title', max_length=255),
        ),
    ]
