# Generated by Django 4.2.9 on 2024-02-21 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_certificate_description_certificate_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='title',
            field=models.CharField(default='Default Title', max_length=255),
        ),
    ]
