# Generated by Django 4.2.9 on 2024-03-06 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_award_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldproperty',
            name='floor_plan',
            field=models.ImageField(blank=True, upload_to='floor_plans/%Y/%m/%d'),
        ),
    ]
