# Generated by Django 4.2.9 on 2024-03-06 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_soldproperty_floor_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldproperty',
            name='video',
            field=models.URLField(blank=True, default='https://www.example.com/default-video-url'),
        ),
    ]
