# Generated by Django 4.2.9 on 2024-03-06 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_alter_soldproperty_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldproperty',
            name='garage',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='soldproperty',
            name='price',
            field=models.CharField(default='0.00', max_length=100),
        ),
    ]
