# Generated by Django 4.2.9 on 2024-03-07 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_soldproperty_address_alter_soldproperty_floor_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackcard',
            name='Owner',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
