# Generated by Django 4.2.9 on 2024-03-18 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_feedbackcard_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='logo_icon',
            field=models.ImageField(default='about_images/default_logo.jpg', upload_to='about_images/'),
        ),
    ]
