# Generated by Django 4.2.9 on 2024-03-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0024_about_logo_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldproperty',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
    ]
