# Generated by Django 4.2.9 on 2024-08-23 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_alter_soldproperty_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldproperty',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
