# Generated by Django 4.2.9 on 2024-08-23 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0026_soldproperty_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldproperty',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
