# Generated by Django 4.2.9 on 2024-08-23 13:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0027_alter_soldproperty_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldproperty',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
