# Generated by Django 4.2.9 on 2024-10-24 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0025_alter_listing_floor_plan'),
        ('pages', '0028_alter_soldproperty_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldproperty',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='soldproperty',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.listing'),
        ),
        migrations.AddField(
            model_name='soldproperty',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='soldproperty',
            name='zipcode',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='soldproperty',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='soldproperty',
            name='bathrooms',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='soldproperty',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='soldproperty',
            name='price',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='soldproperty',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
