# Generated by Django 5.0.6 on 2025-02-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0029_soldproperty_city_soldproperty_listing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='full_content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
