# Generated by Django 5.0.6 on 2025-02-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0030_alter_blog_full_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='background_image3',
            field=models.ImageField(default='about_images/default_logo.jpg', upload_to='about_images/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='full_content',
            field=models.TextField(default='full_content'),
        ),
    ]
