"""
Django settings for webapp project.

Generated by 'django-admin startproject' using Django 2.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

# import os
# from pathlib import Path
# from django.utils.translation import gettext_lazy as _


# # Build paths inside the project like this: os.path.join(BASE_DIR, ...)
# BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# Build paths inside the project like this: BASE_DIR / 'subdir'

from pathlib import Path
from django.utils.translation import gettext_lazy as _
#messages
from django.contrib.messages import constants as messages      #messages




BASE_DIR = Path(__file__).resolve().parent.parent

# Define other paths using BASE_DIR
LOCALE_PATHS = [BASE_DIR / 'locale']


# CSRF verification settings
CSRF_COOKIE_SECURE = True  # Ensure this is true only if using HTTPS
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Strict'
CSRF_TRUSTED_ORIGINS = ['https://khushmonga.com']
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'x0ov4^!p$7^f12o=1ltd+r^$n3tlxy6l8(xyzv#4s8+4k!x!ki'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['khushmonga.com', 'www.khushmonga.com', '54.172.245.112', 'localhost', '127.0.0.1']



# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'corsheaders',
    'django.contrib.sitemaps',
    'pages.apps.PagesConfig',
    'listings.apps.ListingsConfig',
    'realtors.apps.RealtorsConfig',
    'accounts.apps.AccountsConfig',
    'contacts.apps.ContactsConfig',
    'SEO.apps.SeoConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'tinymce',
    'ckeditor',
    'rest_framework',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', #Cors Headers to connect Frontend with backend
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware',  # Add locale middleware for language handling
]

ROOT_URLCONF = 'webapp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'react-app1/dist'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'webapp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        'OPTIONS': {
            'timeout': 50,  # Set timeout
        },
        'CONN_MAX_AGE': 0,  # Ensure idle connections are closed immediately
    }
}




# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.TokenAuthentication',  # For token-based authentication
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',  # Restricts access to authenticated users
    ],
}





# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

# Static files (CSS, JavaScript, images)
# Static and Media files settings
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'static'
STATICFILES_DIRS = [BASE_DIR / 'webapp' / 'static']

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Django CORS settings
CORS_ORIGIN_ALLOW_ALL = True  # Allow requests from all origins
# Or specify specific origins to allow
CORS_ORIGIN_WHITELIST = [
    'https://khushmonga.com',
    # Add other allowed origins as needed
]


CORS_ALLOWED_ORIGINS = [
    'http://localhost:5173',  # React frontend
]
# Or allow all origins (not recommended for production):
CORS_ALLOW_ALL_ORIGINS = True


MESSAGE_TAGS={
    messages.ERROR:'danger',
}

#Email config
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtpout.secureserver.net'  # GoDaddy SMTP server
EMAIL_PORT = 465  # GoDaddy SMTP port
EMAIL_USE_SSL = True  # Use SSL encryption for secure communication
EMAIL_HOST_USER = 'admin@khushmonga.com'  # Your professional email address
EMAIL_HOST_PASSWORD = 'Km270279*'  # Password for your professional email address

# Optional: Set a default 'from' email address for outgoing emails
DEFAULT_FROM_EMAIL = 'admin@khushmonga.com'



# settings.py
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'




TINYMCE_DEFAULT_CONFIG = {
    'height': 360,
    'width': '100%',
    'cleanup_on_startup': True,
    'custom_undo_redo_levels': 20,
    'selector': 'textarea',
    'theme': 'modern',
    'plugins': '''
        textcolor save link image media preview codesample contextmenu
        table code lists fullscreen  insertdatetime nonbreaking
        contextmenu directionality emoticons template paste textcolor
    ''',
    'toolbar': '''
        undo redo | styleselect | bold italic | alignleft aligncenter
        alignright alignjustify | bullist numlist outdent indent | link image
        | preview codesample
    ''',
    'menubar': False,
    'statusbar': True,
}


CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': [
            ['Bold', 'Italic', 'Underline', 'Strike'],  # Basic text styling
            ['NumberedList', 'BulletedList'],  # Ordered and unordered lists
            ['Styles', 'Format', 'Font', 'FontSize'],  # Style options, headings, font, font size
            ['Table', 'HorizontalRule'],  # Table and horizontal line
            ['Link', 'Unlink', 'Anchor'],  # Links and anchors
            ['TextColor'],  # Text color
            ['Emoji', 'SpecialChar'],  # Emoji and special character
            ['Source'],  # Source code view
        ],
    },
}



# Use the Australia/Perth timezone
TIME_ZONE = 'Australia/Perth'

# Use timezone-aware datetimes
USE_TZ = True

# Optional: If you want to enable localization
USE_L10N = True

# settings.py
SITE_DOMAIN = 'http://khushmonga.com'

LANGUAGES = [
    ('en-au', _('Australian English')),
    ('en', _('English (US)')),
    ('fr', _('French')),
]

LANGUAGE_CODE = 'en'  # Default to US English
LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

USE_I18N = True
# Use the Australia/Perth timezone
TIME_ZONE = 'Australia/Perth'

# Use timezone-aware datetimes
USE_TZ = True

# Optional: If you want to enable localization
USE_L10N = True

# HTTPS settings
# SECURE_SSL_REDIRECT = True  # Force HTTPS
SESSION_COOKIE_SECURE = True  # Ensure session cookies are secure
CSRF_COOKIE_SECURE = True  # Ensure CSRF cookies are secure
SITEMAP_PROTOCOL = 'https'  # Use HTTPS for sitemaps
