# Generated by Django 4.2.9 on 2024-02-25 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_registered_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacts',
            options={'verbose_name_plural': 'Contacts'},
        ),
        migrations.AlterModelOptions(
            name='marketappraisal',
            options={'verbose_name_plural': 'Market Appraisals'},
        ),
        migrations.AlterModelOptions(
            name='registered_user',
            options={'verbose_name_plural': 'Registered Users'},
        ),
    ]
