# Generated by Django 4.2.9 on 2024-05-13 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_alter_contacts_options_contacts_source_of_enquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_address', models.CharField(max_length=200)),
                ('full_names', models.CharField(max_length=200)),
                ('current_address', models.CharField(max_length=200)),
                ('bank_borrowing_from', models.CharField(max_length=100)),
                ('percentage_borrowing', models.DecimalField(decimal_places=2, max_digits=5)),
                ('current_savings', models.DecimalField(decimal_places=2, max_digits=10)),
                ('broker_details', models.TextField()),
                ('email_addresses', models.TextField()),
                ('deposit_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('finance_approval_days', models.IntegerField()),
                ('settlement_days', models.IntegerField()),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AlterModelOptions(
            name='contacts',
            options={'verbose_name_plural': 'contacts'},
        ),
    ]
