# Generated by Django 4.2.9 on 2024-05-16 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_propertyoffer_alter_contacts_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='source_of_Enquiry',
        ),
    ]
