# Generated by Django 4.2.9 on 2024-05-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_remove_contacts_source_of_enquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='source_of_Enquiry',
            field=models.CharField(default='website', max_length=200),
        ),
    ]
