# Generated by Django 4.2.9 on 2024-05-16 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0009_contacts_source_of_enquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyoffer',
            name='email_addresses',
            field=models.EmailField(max_length=254),
        ),
    ]
