# Generated by Django 4.2.9 on 2024-05-16 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0010_alter_propertyoffer_email_addresses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertyoffer',
            old_name='email_addresses',
            new_name='email_address',
        ),
    ]
