# Generated by Django 4.2.9 on 2024-05-17 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0011_rename_email_addresses_propertyoffer_email_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertyoffer',
            old_name='full_names',
            new_name='buyer1',
        ),
        migrations.RenameField(
            model_name='propertyoffer',
            old_name='email_address',
            new_name='email_buyer1',
        ),
        migrations.RemoveField(
            model_name='propertyoffer',
            name='percentage_borrowing',
        ),
        migrations.AddField(
            model_name='propertyoffer',
            name='buyer2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='propertyoffer',
            name='email_buyer2',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='propertyoffer',
            name='percentage_borrowing_or_cash_offer',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertyoffer',
            name='pre_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='propertyoffer',
            name='deposit_amount',
            field=models.CharField(max_length=20),
        ),
    ]
