# Generated by Django 4.2.9 on 2024-05-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0012_rename_full_names_propertyoffer_buyer1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyoffer',
            name='current_savings',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='propertyoffer',
            name='deposit_amount',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='propertyoffer',
            name='finance_approval_days',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='propertyoffer',
            name='pre_approval',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='propertyoffer',
            name='purchase_price',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='propertyoffer',
            name='settlement_days',
            field=models.CharField(max_length=20),
        ),
    ]
