# Generated by Django 4.2.9 on 2024-07-19 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0013_alter_propertyoffer_current_savings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyoffer',
            name='contact_number',
            field=models.CharField(default='123-456-7890', max_length=15),
        ),
    ]
