# Generated by Django 4.2.9 on 2024-07-20 16:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0014_propertyoffer_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyoffer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
