# Generated by Django 4.2.9 on 2024-08-08 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0015_propertyoffer_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Old_Data_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(default='0', max_length=20)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
            ],
        ),
    ]
