# Generated by Django 5.0.6 on 2025-02-16 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0016_old_data_list'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacts',
            options={'verbose_name_plural': 'Enquiries'},
        ),
    ]
