# Generated by Django 4.2.9 on 2024-08-27 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetaDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(choices=[('index', 'Home'), ('listings', 'Listings'), ('coming_soon', 'Coming Soon'), ('about', 'About'), ('blog_list', 'Blogs'), ('sold_properties', 'Sold Properties'), ('testimonials', 'Testimonials')], max_length=100, unique=True)),
                ('meta_description', models.TextField()),
            ],
            options={
                'verbose_name': 'Meta Description',
                'verbose_name_plural': 'Meta Descriptions',
            },
        ),
    ]
