# Generated by Django 4.2.9 on 2024-08-27 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SEO', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadescription',
            name='page_name',
            field=models.TextField(choices=[('index', 'Home'), ('listings', 'Listings'), ('coming_soon', 'Coming Soon'), ('about', 'About'), ('blog_list', 'Blogs'), ('sold_properties', 'Sold Properties'), ('testimonials', 'Testimonials')], unique=True),
        ),
    ]
